//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manage.Web.ServiceFileClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFileInfo", Namespace="http://schemas.datacontract.org/2004/07/Manage.WcfService.Services")]
    [System.SerializableAttribute()]
    public partial class CustomFileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SendByteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendByteStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.FileSizeField, value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewName {
            get {
                return this.NewNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NewNameField, value) != true)) {
                    this.NewNameField = value;
                    this.RaisePropertyChanged("NewName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldName {
            get {
                return this.OldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OldNameField, value) != true)) {
                    this.OldNameField = value;
                    this.RaisePropertyChanged("OldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SendByte {
            get {
                return this.SendByteField;
            }
            set {
                if ((object.ReferenceEquals(this.SendByteField, value) != true)) {
                    this.SendByteField = value;
                    this.RaisePropertyChanged("SendByte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendByteStr {
            get {
                return this.SendByteStrField;
            }
            set {
                if ((object.ReferenceEquals(this.SendByteStrField, value) != true)) {
                    this.SendByteStrField = value;
                    this.RaisePropertyChanged("SendByteStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFileClient.IServiceFile")]
    public interface IServiceFile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/UpLoadFileInfo", ReplyAction="http://tempuri.org/IServiceFile/UpLoadFileInfoResponse")]
        Manage.Web.ServiceFileClient.CustomFileInfo UpLoadFileInfo(Manage.Web.ServiceFileClient.CustomFileInfo fileInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/UpLoadFileInfo", ReplyAction="http://tempuri.org/IServiceFile/UpLoadFileInfoResponse")]
        System.Threading.Tasks.Task<Manage.Web.ServiceFileClient.CustomFileInfo> UpLoadFileInfoAsync(Manage.Web.ServiceFileClient.CustomFileInfo fileInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/DeleteFile", ReplyAction="http://tempuri.org/IServiceFile/DeleteFileResponse")]
        Manage.Web.ServiceFileClient.CustomFileInfo DeleteFile(Manage.Web.ServiceFileClient.CustomFileInfo fileInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/DeleteFile", ReplyAction="http://tempuri.org/IServiceFile/DeleteFileResponse")]
        System.Threading.Tasks.Task<Manage.Web.ServiceFileClient.CustomFileInfo> DeleteFileAsync(Manage.Web.ServiceFileClient.CustomFileInfo fileInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceFileChannel : Manage.Web.ServiceFileClient.IServiceFile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceFileClient : System.ServiceModel.ClientBase<Manage.Web.ServiceFileClient.IServiceFile>, Manage.Web.ServiceFileClient.IServiceFile {
        
        public ServiceFileClient() {
        }
        
        public ServiceFileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceFileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Manage.Web.ServiceFileClient.CustomFileInfo UpLoadFileInfo(Manage.Web.ServiceFileClient.CustomFileInfo fileInfo) {
            return base.Channel.UpLoadFileInfo(fileInfo);
        }
        
        public System.Threading.Tasks.Task<Manage.Web.ServiceFileClient.CustomFileInfo> UpLoadFileInfoAsync(Manage.Web.ServiceFileClient.CustomFileInfo fileInfo) {
            return base.Channel.UpLoadFileInfoAsync(fileInfo);
        }
        
        public Manage.Web.ServiceFileClient.CustomFileInfo DeleteFile(Manage.Web.ServiceFileClient.CustomFileInfo fileInfo) {
            return base.Channel.DeleteFile(fileInfo);
        }
        
        public System.Threading.Tasks.Task<Manage.Web.ServiceFileClient.CustomFileInfo> DeleteFileAsync(Manage.Web.ServiceFileClient.CustomFileInfo fileInfo) {
            return base.Channel.DeleteFileAsync(fileInfo);
        }
    }
}
