//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manage.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManageDBEntities : DbContext
    {
        public ManageDBEntities()
            : base("name=ManageDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sys_Permission> Sys_Permission { get; set; }
        public virtual DbSet<Sys_PermissionRole> Sys_PermissionRole { get; set; }
        public virtual DbSet<Sys_Role> Sys_Role { get; set; }
        public virtual DbSet<Sys_RoleUser> Sys_RoleUser { get; set; }
        public virtual DbSet<Sys_UserGroup> Sys_UserGroup { get; set; }
        public virtual DbSet<Sys_UserGroupRole> Sys_UserGroupRole { get; set; }
        public virtual DbSet<Sys_UserGroupUser> Sys_UserGroupUser { get; set; }
        public virtual DbSet<Sys_Module> Sys_Module { get; set; }
        public virtual DbSet<Sys_User> Sys_User { get; set; }
    }
}
